dist: xenial
language: java
jdk:
- openjdk11
script:
- "./gradlew clean build"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: releases
  api_key:
    secure: ah3Bmxe0GQB2wMCyWx52prpCoJ20dmwcfDZp6WM2YWpaOzBrCoMHgSWqDExKBAAgVQNOJn6RxOQuvOgTQ8NDuSikcvFMV+o6mSBh9lIAfU3NgjzQc9RtB4PMzTwDnd19dAixvoGgoi9ZJa9F0+0w2YVh9UH0jio3rzlIxafTS5iPxAaGZf1kJip5+g0SCAqRPZJb+5RlkSC5wUlRSMsx+YPBtYrHDLTI1bX6OCeGIE/HhpFG7Zi/KwYOdjXx2LZfLV5cL3ggBFS7Rml7kFI3QKNcifafov9AoF2G6eQhqS9qvTskhfcVpRd7BNuAdXHl/tweAjUook4U1CT1CheU8aOP7FyroyxonJs+ne/OnxL0aU/9pA2XHwTIpZfx5F0cHtCTXSTRObZSc/MrZbOaGt90rtGpoANNcgNV7FnLKDkSmYu8hNuD6hKWQu/QNb+s866zQhUMmqHE46sqtyUdxgIGqpqErLzf4A+Z6Y/kbX+cNwdOURc8aF1jGvadJgkL0XEHsYkwD/l48sfrKzQIV3Dul/SJm1xFYEjDO3YU/cqwr8eJrVOfQBqN04KAiLep5YNgVi8OirWlciWpbyjDOl4aqXYH5xoSRCC2LPzVhnTkUuov/B1LDadctuUdWIHgf3eaDdDLwIBGXA9iMHCl9RVdHJOXplYCJ2d4J9pLza0=
  file_glob: true
  file:
    - "/home/travis/build/pacphi/cf-butler/build/libs/*"
  skip_cleanup: true
  on:
    repo: pacphi/cf-butler
    tags: true
