cf:
  apiHost: api.run.pivotal.io
  username: you@mail.me
  password: xxxxxx
  organizationBlackList:
    - system

logging:
  level:
    org.springframework: INFO
    org.cloudfoundry.reactor: DEBUG

# Set schedule for this task to adhere to
# @see https://crontab.guru for help, first parameter is seconds
cron:
  collection: "0 0 0 * * *"

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,scheduledtasks,loggers,prometheus
